### ISSUE TITLE
`npm install` fails with `EINVALIDTAGNAME`

### ISSUE THREAD

**Issue by brikelly** [Authress/express-starter-kit#1]
Mac M1, node v18.17.1 (npm v10.2.5)

Running `npm install` in a freshly cloned repo yields the following result:

```[main][~/code/express-starter-kit]$ npm install  
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: express-starter-kit@1.0.0
npm WARN Found: typescript@5.3.3
npm WARN node_modules/typescript
npm WARN   dev typescript@"^4.9.5" from the root project
npm WARN   3 more (ts-node, ts-node, ts-node-dev)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer typescript@">=^3.9.3" from ts-node-esm@0.0.6
npm WARN node_modules/ts-node-esm
npm WARN   dev ts-node-esm@"^0.0.6" from the root project
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name ">=^1.2.5" of package "@swc/core@>=^1.2.5": Tags may not have any characters that encodeURIComponent encodes.```

**Comment by wparad** [comment]
wow, thanks for finding that. It turns out typescript doesn't really work well with node, shocker really. And one of the packages that supported this appears to be just be hard broken. Weirdly this works with `yarn`. This is a pretty esoteric problem, I've never seen this come up before in any other service/package. /shrug

I'm going to push up a PR to fix this, so no one runs into this problem again.

**Comment by brikelly** [comment]
Thanks for the fast fix! Works great now :)
